cosmos_db_endpoint : "https://news-app.documents.azure.com:443/"
cosmos_db_key : "m08hEJ1dCfXAGTorIMzY6Y6wYac5aaoh2bJdqAcKTw3IiIKtvbIZoFcmQTI2UFPIeT2bDfjxIlmOACDb8AK54g=="
database_name : "News"
container_name : "Articles"
openai_endpoint : "https://richag-openai.openai.azure.com/"
openai_key : "3dca3bbca856436bb23bf192506c924f"
openai_type : "azure"
openai_api_version : "2023-05-15"
openai_embeddings_deployment : "richag-embedding-deployment"
openai_embeddings_model : "text-embedding-3-large"
openai_embeddings_dimensions : "256"
openai_completions_deployment : "richag-completions-model"
openai_completions_model : "gpt-4o"